name: Run Cypress Tests

on:
  push:
    branches:
      - master # Executa testes em pushs para a branch main
  pull_request:
    branches:
      - master # Executa testes em PRs para a branch main

jobs:
  cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Escolha a versão do Node.js compatível com seu projeto

      # 3. Cache de dependências Node.js
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Instalar dependências do projeto
      - name: Install dependencies
        run: npm ci # Use 'ci' para instalações rápidas e consistentes

      # 5. Instalar Cypress (se necessário)
      - name: Install Cypress
        run: npx cypress install

      # 6. Configuração de um servidor (opcional, caso seu app use um servidor)
      - name: Start the application
        run: npm start &
        env:
          CI: true

      # 7. Executar testes do Cypress
      - name: Run Cypress Tests
        run: npx cypress run --config-file src/cypress.config.js
